export const GET_USER = 'GET_USER';
export const INCREMENT_SCORE = 'INCREMENT_SCORE';
export const GET_ASSERTIONS = 'GET_ASSERTIONS';
export const RESET_USER = 'RESET_USER';
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_DIFFICULTY = 'GET_DIFFICULTY';
export const GET_AMOUNT = 'GET_AMOUNT';
export const RESET_SETTINGS = 'RESET_SETTINGS';
